#!/bin/sh
MIDNIGHT=$(date -d "today 00:00" "+%s")
MIDNIGHTYESTER=$(date -d "yesterday 00:00" "+%s")
ENTRIES=15

URL="https://hn.algolia.com/api/v1/search?&numericFilters=created_at_i>$MIDNIGHTYESTER,created_at_i<$MIDNIGHT&hitsPerPage=$ENTRIES"

curl --retry 5 --retry-delay 0 --silent "$URL" && exit 0 || exit 1 # in case of error, abort
